// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBnWQsdyrXO8iofUtYvpbzrEH3BEDx4xI',
    appId: '1:28315668504:web:c67d3ae4b85e6a37a2f36d',
    messagingSenderId: '28315668504',
    projectId: 'mobile-app-asignment-1',
    authDomain: 'mobile-app-asignment-1.firebaseapp.com',
    storageBucket: 'mobile-app-asignment-1.appspot.com',
    measurementId: 'G-ZP9K0KVJL1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuX3XI3ofwITqy8xpyGWgEItXYtESGq-o',
    appId: '1:28315668504:android:71fd15d6491c8847a2f36d',
    messagingSenderId: '28315668504',
    projectId: 'mobile-app-asignment-1',
    storageBucket: 'mobile-app-asignment-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWyhJebhIysW6wljGHTE88PtesW4w_3u0',
    appId: '1:28315668504:ios:c6091a60c7dedb7fa2f36d',
    messagingSenderId: '28315668504',
    projectId: 'mobile-app-asignment-1',
    storageBucket: 'mobile-app-asignment-1.appspot.com',
    iosBundleId: 'com.example.mobileAssignment1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWyhJebhIysW6wljGHTE88PtesW4w_3u0',
    appId: '1:28315668504:ios:06ef6d0f3fd1b634a2f36d',
    messagingSenderId: '28315668504',
    projectId: 'mobile-app-asignment-1',
    storageBucket: 'mobile-app-asignment-1.appspot.com',
    iosBundleId: 'com.example.mobileAssignment1.RunnerTests',
  );
}
